GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Mary Poppendieck blog",
  "author": "Mary Poppendieck1",
  "url": "/mary_poppendieck",
  "likes": 2
}

###
POST http://localhost:3001/api/person/ HTTP/1.1
content-type: application/json

{
    "number": "23445566"
}

###
POST http://localhost:3001/api/person/ HTTP/1.1
content-type: application/json

{
    "name": "Dima"
}